# Generated by Django 4.2.2 on 2023-07-08 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vote',
        ),
    ]
