# Generated by Django 4.2.2 on 2023-07-09 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_delete_vote'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='vote_tally',
            new_name='votes',
        ),
    ]
